CREATE TABLE IF NOT EXISTS users (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 username text NOT NULL,
 password_hash text NOT NULL
);
CREATE TABLE IF NOT EXISTS sessions (
 token_hash text PRIMARY KEY,
 user_id bigint NOT NULL REFERENCES users(id),
 expires_at timestamptz NOT NULL
);
CREATE TABLE IF NOT EXISTS services (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name text NOT NULL,
 duration_minutes integer NOT NULL CHECK (duration_minutes > 0)
);
CREATE TABLE IF NOT EXISTS specialists (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name text NOT NULL,
 service_ids integer[] NOT NULL
);
CREATE TABLE IF NOT EXISTS slots (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 specialist_id bigint NOT NULL REFERENCES specialists(id),
 start_at timestamptz NOT NULL,
 end_at timestamptz NOT NULL,
 CHECK (end_at > start_at)
);
CREATE TABLE IF NOT EXISTS appointments (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 slot_id bigint NOT NULL REFERENCES slots(id),
 service_id bigint NOT NULL REFERENCES services(id),
 specialist_id bigint NOT NULL REFERENCES specialists(id),
 client_name text NOT NULL,
 start_at timestamptz NOT NULL,
 end_at timestamptz NOT NULL,
 status text NOT NULL CHECK (status IN ('active','cancelled')),
 created_at timestamptz NOT NULL DEFAULT now(),
 cancelled_at timestamptz,
 CHECK (end_at > start_at)
);

-- Upgrade the initial local draft to the assignment baseline: no secondary indexes.
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_username_key;
